# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.14.4
minecraft_version_range=[1.14.4]
forge_version=28.2.26
forge_version_range=[28,)
loader_version_range=[28,)
mapping_channel=snapshot
mapping_version=20190719-1.14.3
mcp_version=20190829.143755

mod_id=orespawn
mod_name=MMD OreSpawn
mod_license=LGPL-2.1
mod_version=4.0.6.114041
mod_group_id=zone.moddev.mc.orespawn
mod_authors=SkyBlade1978, dshadowwolf, the MMD Team
mod_description=Configurable, provider-driven terrain, ore, and deposit generation.
